### ISSUE TITLE
Chinese lemmatization

### ISSUE THREAD

**Issue by interlark** [jmnybl/universal-lemmatizer#1]
I wonder why universal-lemmatizer gave not that well scores about **zh_gsd** according to
 [conll18 results](http://universaldependencies.org/conll18/results-lemmas.html). Is it possible to improve chinese lemmatization somehow?

**Comment by jmnybl** [comment]
Hi,

I have just updated a new version of our paper here https://arxiv.org/pdf/1902.00972.pdf, including lemmatization evaluation both with gold and predicted segmentation. In Chinese (zh_gsd) the problem seems to be segmentation, i.e. lemma is wrong if there is a segmentation error. With gold segmentation, lemmatization accuracy is 100%. I don't know much about Chinese, but with this treebank lemmatization seems to be trivial.
